### ISSUE TITLE
forge is going dev--can we freeze git pulls?

### ISSUE THREAD

**Issue by rafstahelin** [ashleykleynhans/forge-docker#1]
Illyasviel announcement means everything will break if updated. Can we freeze Forge on launch?!
[[lllyasviel](https://github.com/lllyasviel)](https://github.com/lllyasviel/stable-diffusion-webui-forge/discussions/801)

**Comment by ashleykleynhans** [comment]
I already pushed a change yesterday so that it doesn't auto update itself anymore in version 3.0.1.

**Comment by rafstahelin** [comment]
you're way ahead of me then. I tried creating a pod with Forge with my existing net volume but i am not able to open the forge webui 

I get

![image](https://github.com/ashleykleynhans/forge-docker/assets/64715158/bb7b0fd3-d17b-4088-9a2a-cecb16674b81)

I get `The port is not up yet`

I suspect it maybe be something with the installation i had. I've tried closing and starting a new pod for my volume. 

What can i do to debug? thx

**Comment by ashleykleynhans** [comment]
Check the container logs, not the system logs.  Its probably still syncing to /workspace.

**Comment by rafstahelin** [comment]
I did see the syncing being done

**Comment by rafstahelin** [comment]
![image](https://github.com/ashleykleynhans/forge-docker/assets/64715158/37860803-22f8-4a92-a284-553b34f1ddd7)

![image](https://github.com/ashleykleynhans/forge-docker/assets/64715158/4b5d0b16-12fe-4e42-9ad2-c4aa6715b7b7)


what should I do? Should I delete the venv and restart?

**Comment by ashleykleynhans** [comment]
Check the log file for any errors: /workspace/logs/forge.log

**Comment by rafstahelin** [comment]
```

################################################################
[1m[32mInstall script for stable-diffusion + Web UI
[1m[34mTested on Debian 11 (Bullseye), Fedora 34+ and openSUSE Leap 15.4 or newer.[0m
################################################################

################################################################
Running on [1m[32mroot[0m user
################################################################

################################################################
Repo already cloned, using it as install directory
################################################################

################################################################
python venv already activate or run without venv: /workspace/venvs/stable-diffusion-webui-forge
################################################################

################################################################
Launching launch.py...
################################################################
glibc version is 2.35
Check TCMalloc: libtcmalloc_minimal.so.4
libtcmalloc_minimal.so.4 is linked with libc.so,execute LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libtcmalloc_minimal.so.4
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
Version: f0.0.17v1.8.0rc-latest-277-g0af28699c
Commit hash: 0af28699c45c1c5bf9cb6818caac6ce881123131
Installing sd-forge-controlnet requirement: changing opencv-python version from 4.10.0.82 to 4.8.0
Installing forge_legacy_preprocessor requirement: changing opencv-python version from 4.10.0.82 to 4.8.0
Legacy Preprocessor init warning: Unable to install insightface automatically. Please try run `pip install insightface` manually.
Launching Web UI with arguments: -f --port 3001 --listen --api --xformers --enable-insecure-extension-access --no-half-vae --ckpt-dir /workspace/training_gr4ph1cw/models
Total VRAM 24217 MB, total RAM 515799 MB
xformers version: 0.0.26.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : native
Hint: your device supports --pin-shared-memory for potential speed improvements.
Hint: your device supports --cuda-malloc for potential speed improvements.
Hint: your device supports --cuda-stream for potential speed improvements.
VAE dtype: torch.bfloat16
CUDA Stream Activated:  False
Using xformers cross attention
```
not sure i see an error here???

**Comment by rafstahelin** [comment]
Does this maybe look like forge is up but I don't have access to the port?

**Comment by ashleykleynhans** [comment]
Yeah there are no errors, but doesn't look like its completed starting up either.  Maybe its just slow to start on the network volume.

> Does this maybe look like forge is up but I don't have access to the port?

Probably still busy starting up, give it a bit more time.

**Comment by rafstahelin** [comment]
Yea, this pod is slow but I’ve left it opening for 30mn. It’s just weird.
Usually much faster

thanks

best regards, raf

**Comment by rafstahelin** [comment]
![image](https://github.com/ashleykleynhans/forge-docker/assets/64715158/33585f1e-fc8c-4c81-9e6a-02a1e82111ea)

it's taking dog years. Should i just delete the venv and try again? 

Previous attempt, container started but then no connection to port 3000

I've been trying all day to get Forge to work. Kohya image works fine on the same volume

**Comment by ashleykleynhans** [comment]
Its a problem with the internet speed of the pod, nothing to do with the template, contact RunPod about it.

**Comment by rafstahelin** [comment]
Yea I got in touch with
Looks like a speed freak show. Nothing they want to talk about

**Comment by ashleykleynhans** [comment]
I usually avoid secure cloud and network volumes because of this and just use community cloud.  Community cloud is significantly faster.

**Comment by rafstahelin** [comment]
totally makes sense. Just thinking, would there be a way to set a env variable to turn off downloading of models that takes all the weight of downloading for network volumes, since in volumes we always already have the model safetensors on disk? Might take a bit of the burden off of creating the image? Dont even know if this is even possible

**Comment by ashleykleynhans** [comment]
> totally makes sense. Just thinking, would there be a way to set a env variable to turn off downloading of models that takes all the weight of downloading for network volumes, since in volumes we always already have the model safetensors on disk? Might take a bit of the burden off of creating the image? Dont even know if this is even possible

It only does a new sync if the template version changes in case there are some new requirements in the venv that need to be synced etc.  It shoudn't download anything , just syncs files from the container disk to /workspace.

**Comment by rafstahelin** [comment]
cool, thank you

Ok i am going to start a new volume and delete this oen. I think this one might be compromised not sure how. But just to check with you again. It's fine to install  your Kohya, Forge, and Ultimate templates in the same Network VOlume right? It shouldnt conflict in any way since everything is in separate folders

**Comment by rafstahelin** [comment]
i mean the logs show it is ready. Jupyter loads, but Forge doesnt

**Comment by ashleykleynhans** [comment]
> cool, thank you
> 
> Ok i am going to start a new volume and delete this oen. I think this one might be compromised not sure how. But just to check with you again. It's fine to install your Kohya, Forge, and Ultimate templates in the same Network VOlume right? It shouldnt conflict in any way since everything is in separate folders

Yes its fine, they each create their own venv directory in a different path now, not the same path anymore.

**Comment by ashleykleynhans** [comment]
> i mean the logs show it is ready. Jupyter loads, but Forge doesnt

Check the forge.log log file for any errors, probably just slow to start up.

**Comment by rafstahelin** [comment]
the thing is the speed is back. I am downloading my kohya models very fast. jupyter went up fine. But now after 30mn still no forge. does seem like something else is up

Here's the log:
```

################################################################
[1m[32mInstall script for stable-diffusion + Web UI
[1m[34mTested on Debian 11 (Bullseye), Fedora 34+ and openSUSE Leap 15.4 or newer.[0m
################################################################

################################################################
Running on [1m[32mroot[0m user
################################################################

################################################################
Repo already cloned, using it as install directory
################################################################

################################################################
python venv already activate or run without venv: /workspace/venvs/stable-diffusion-webui-forge
################################################################

################################################################
Launching launch.py...
################################################################
glibc version is 2.35
Check TCMalloc: libtcmalloc_minimal.so.4
libtcmalloc_minimal.so.4 is linked with libc.so,execute LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libtcmalloc_minimal.so.4
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
Version: f0.0.17v1.8.0rc-latest-277-g0af28699c
Commit hash: 0af28699c45c1c5bf9cb6818caac6ce881123131
Installing sd-forge-controlnet requirement: changing opencv-python version from 4.10.0.82 to 4.8.0
Installing forge_legacy_preprocessor requirement: changing opencv-python version from 4.10.0.82 to 4.8.0
Legacy Preprocessor init warning: Unable to install insightface automatically. Please try run `pip install insightface` manually.
Launching Web UI with arguments: -f --port 3001 --listen --api --xformers --enable-insecure-extension-access --no-half-vae --ckpt-dir /workspace/training_gr4ph1cw/models
Total VRAM 24217 MB, total RAM 515799 MB
xformers version: 0.0.26.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : native
Hint: your device supports --pin-shared-memory for potential speed improvements.
Hint: your device supports --cuda-malloc for potential speed improvements.
Hint: your device supports --cuda-stream for potential speed improvements.
VAE dtype: torch.bfloat16
CUDA Stream Activated:  False
Using xformers cross attention
```

**Comment by rafstahelin** [comment]
ok, i just created a new networkf volume with your forge. Forge is not going up

**Comment by ashleykleynhans** [comment]
> the thing is the speed is back. I am downloading my kohya models very fast. jupyter went up fine. But now after 30mn still no forge. does seem like something else is up
> 
> Here's the log:
> 
> ```
> 
> ################################################################
> �[1m�[32mInstall script for stable-diffusion + Web UI
> �[1m�[34mTested on Debian 11 (Bullseye), Fedora 34+ and openSUSE Leap 15.4 or newer.�[0m
> ################################################################
> 
> ################################################################
> Running on �[1m�[32mroot�[0m user
> ################################################################
> 
> ################################################################
> Repo already cloned, using it as install directory
> ################################################################
> 
> ################################################################
> python venv already activate or run without venv: /workspace/venvs/stable-diffusion-webui-forge
> ################################################################
> 
> ################################################################
> Launching launch.py...
> ################################################################
> glibc version is 2.35
> Check TCMalloc: libtcmalloc_minimal.so.4
> libtcmalloc_minimal.so.4 is linked with libc.so,execute LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libtcmalloc_minimal.so.4
> Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
> Version: f0.0.17v1.8.0rc-latest-277-g0af28699c
> Commit hash: 0af28699c45c1c5bf9cb6818caac6ce881123131
> Installing sd-forge-controlnet requirement: changing opencv-python version from 4.10.0.82 to 4.8.0
> Installing forge_legacy_preprocessor requirement: changing opencv-python version from 4.10.0.82 to 4.8.0
> Legacy Preprocessor init warning: Unable to install insightface automatically. Please try run `pip install insightface` manually.
> Launching Web UI with arguments: -f --port 3001 --listen --api --xformers --enable-insecure-extension-access --no-half-vae --ckpt-dir /workspace/training_gr4ph1cw/models
> Total VRAM 24217 MB, total RAM 515799 MB
> xformers version: 0.0.26.post1
> Set vram state to: NORMAL_VRAM
> Device: cuda:0 NVIDIA GeForce RTX 4090 : native
> Hint: your device supports --pin-shared-memory for potential speed improvements.
> Hint: your device supports --cuda-malloc for potential speed improvements.
> Hint: your device supports --cuda-stream for potential speed improvements.
> VAE dtype: torch.bfloat16
> CUDA Stream Activated:  False
> Using xformers cross attention
> ```

Its still starting up, you have to wait.

**Comment by rafstahelin** [comment]
testing a new network volume with forge template. one sec

**Comment by rafstahelin** [comment]
i honestly dont think Forge will work anymore in your template. Its been 35mn and it still is not loading
it just doesnt make sense

**Comment by rafstahelin** [comment]
![image](https://github.com/ashleykleynhans/forge-docker/assets/64715158/3ba06170-d925-4d67-83b1-6a05232b76d3)

still nothing after 35mn loading

that to me is a fail

And the speed of the pod is fine

**Comment by ashleykleynhans** [comment]
****

> i honestly dont think Forge will work anymore in your template. Its been 35mn and it still is not loading it just doesnt make sense

Works fine for me in community cloud, its a RunPod issue nothing wrong with the template.  I can't help that RunPod provides utter shit service. Please go complain to them, you are wasting my time and getting blocked now, goodbye.
